on:
  push:
  
jobs:
  flake-validation:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - uses: DeterminateSystems/flake-checker-action@v12
        with:
          send-statistics: false
